server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/demotest
    type: com.alibaba.druid.pool.DruidDataSource

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER



